export const GenderSelectStyles = {
  control: (provided, state) => ({
    ...provided,
    padding: "0 14px",
    borderRadius: "30px",
    border: "none",
    backgroundColor: "#ffffff",
    cursor: "pointer",
    height: "48px",
    width: "190px",
    boxShadow: "none",
    outline: "none",
    display: "flex",
    alignItems: "center",
  }),
  singleValue: (provided, state) => ({
    ...provided,
    color: "#262626",
    margin: 0,
    padding: 0,
  }),
  option: (provided, state) => ({
    ...provided,
    color: state.isSelected ? "#f6b83d" : "rgba(38, 38, 38, 0.6)",
    backgroundColor: "transparent",
    paddingBottom: "0",
    cursor: "pointer",
    textAlign: "left",
    fontSize: "16px",
    lineHeight: 1.25,
    fontWeight: "500",
    fontFamily: "Inter, sans-serif",
    "&:hover": {
      backgroundColor: "transparent",
      color: "#191a15",
    },
  }),
  menu: (provided) => ({
    ...provided,
    borderRadius: "15px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
    width: "190px",
    top: "100%",
    left: 0,
    right: "auto",
    position: "absolute",
    marginTop: "4px",
  }),
  menuList: (provided) => ({
    ...provided,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "14px",
    maxHeight: "200px",
    overflowY: "auto",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  }),
  placeholder: (provided) => ({
    ...provided,
    color: "#262626",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    margin: 0,
    fontFamily: "Inter, sans-serif",
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
  dropdownIndicator: (provided, state) => ({
    ...provided,
    color: "#262626",
    padding: "0",
    "&:hover": {
      color: "#262626",
    },
    transition: "transform 0.3s ease",
    transform: state.menuIsOpen ? "rotate(180deg)" : "rotate(0deg)",
  }),
};
